env:
  node: true
extends: 
  - airbnb
parser: babel-eslint
parserOptions:
  ecmaVersion: 7
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
  sourceType: module
rules:
  semi: 
    - error
    - never